### PR TITLE
EN-3976 - Add num_points function to SoQL

### PR DESCRIPTION
**Pull request by urmilan**

### CODE REVIEW

**Comment by chitang** [comment]
lgtm

**Comment by chrismetcalf** [comment]
@urmilan OK you've got my attention. What does this one do and how is it different than `count(...)`?

**Comment by AEscobarCruz** [comment]
@chrismetcalf I believe it counts how many vertices there are in a polygon.

**Comment by chrismetcalf** [comment]
@AEscobarCruz And you'd call it something like `$select=NUM_POINTS(geo_column) AS how_many_corners`?

**Comment by chrismetcalf** [comment]
ETA in production?

**Pull request merged**
